name: Build Docker Image

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest
    container:
      image: node

    steps:
      - uses: actions/checkout@v1
      - name: Install
        run: |
          npm install
  cd:
    runs-on: ubuntu-latest
    needs: ci

    steps:
      - uses: actions/checkout@v1
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASS }}
      - name: Build
        run: docker build -t ${{ secrets.SERVICE_NAME }} .
      - name: Tags
        run: |
          docker tag ${{ secrets.SERVICE_NAME }} ${{ secrets.DOCKER_USERNAME }}/${{ secrets.SERVICE_NAME }}:latest
      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.SERVICE_NAME }}:latest
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASS }}
          port: ${{ secrets.PORT }}
          script: |
            echo godigital2020 | sudo -S docker stop $(sudo -S docker ps -a -q)
            echo godigital2020 | sudo -S docker login -u muinde -p geofrey7543
            echo godigital2020 | sudo -S docker pull muinde/user-service:latest
            echo godigital2020 | sudo -S docker run -dit -p 8001:8001 muinde/user-service:latest
